# Generated by Django 2.0.4 on 2018-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('Day', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Holiday', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
